name: A2-CDic-l_x4
distortion: sr
scale: 4
use_tb_logger: false
model: ref-rec     # joint-rec / ref-rec
data1: True  # ref-rec reconstruct the first modal
gpu_ids: [0]
dist: True
dwt: False
mode: IXI
k_loss: False

datasets:
  train:
    mode: IXI
    task: sr       # sr / rec
    scale: 4
    interval_list: [1]
    random_reverse: true
    border_mode: false
    dataroot_GT: root_path/T2
    # dataroot_GT: root_path/T1_train
    use_shuffle: true
    n_workers: 2 
    batch_size: 6
    crop_size: 256
    use_flip: True
    use_rot: True
    hr_in: True
  
  val:
    mode: IXI
    task: sr       # sr / rec
    scale: 4
    test_size: 256
    dataroot_GT: /root_path/test/T2
    # dataroot_GT: root_path/T1_test
    hr_in: True


network_G:
  which_model_G: A2-CDic-l

path:
  pretrain_model_G: ~
  strict_load: False
  resume_state: ~
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  warmup_iter: -1
  T_period: [200000]
  restarts: [200000]
  restart_weights: [1]
  eta_min: !!float 1e-5

  pixel_criterion: l1
  pixel_weight: 1.0
  val_freq: !!float 1000

  manual_seed: 0

logger:
  print_freq: 10
  save_checkpoint_freq: !!float 5000
  
